from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class AppState(BaseModel):
    """
    The state of the application, managed by Pydantic for type safety and validation.
    """
    user_request: str = Field(description="The initial request from the user.")
    
    plan: Optional[Dict[str, Any]] = Field(default=None, description="The execution plan generated by the planning agent.")
    
    perception_data: Optional[Dict[str, Any]] = Field(default=None, description="Data collected by the perception agent.")
    
    market_commentary: Optional[str] = Field(default=None, description="Market commentary generated by the decision agent.")
    
    features_for_forecasting: Optional[List[str]] = Field(default=None, description="Features selected for the forecasting model.")
    
    forecast_result: Optional[Dict[str, Any]] = Field(default=None, description="The final forecast result.")

    # New fields for dynamic workflow control
    next_step: Optional[str] = Field(default=None, description="The next agent to execute.")
    error_message: Optional[str] = Field(default=None, description="Any error message that occurred.")